### ISSUE TITLE
Créer un model (interface et schema) “adressBar”

### ISSUE THREAD

**Issue by Lorenzomp** [galliotl/Barty#31]
Créer un model (interface et schema) “adressBar” qui contiennent les champs [streetAdress: string; city: string;state:string;postalCode:number;country:string]
et utiliser ce schéma à la place de String pour stocker les adresses des bars

**Comment by galliotl** [comment]
@Lorenzomp L'adresse est unique au bar, elle ne sera réutilisée nulle part ailleurs. Il vaut mieux peut etre que tu remplace le champ addresse du bar de string vers un objet qui contient ce que tu veux
