### ISSUE TITLE
Regex verification

### ISSUE THREAD

**Issue by Lorenzomp** [galliotl/Barty#35]
Mettre en place des vérifications regex sur les différents champs des méthodes createBarController et userSignupController

**Comment by galliotl** [comment]
Ouais super idée! probablement que y a des libraries existantes qui le font très bien !! Est-ce que y en a un de vous @Lorenzomp  @TimUtt  qui peut regarder?

**Comment by Lorenzomp** [comment]
J'ai pas trouvé de truc correspondant vraiment à mes attentes mes je vais le faire à la main
